// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/errors/v1/errors.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserErrorReason int32

const (
	// 用户相关错误
	UserErrorReason_USER_UNSPECIFIED     UserErrorReason = 0
	UserErrorReason_USER_NOT_FOUND       UserErrorReason = 1
	UserErrorReason_USER_ALREADY_EXISTS  UserErrorReason = 2
	UserErrorReason_EMAIL_ALREADY_EXISTS UserErrorReason = 3
	UserErrorReason_INVALID_CREDENTIALS  UserErrorReason = 4
	UserErrorReason_USER_INACTIVE        UserErrorReason = 5
	UserErrorReason_INVALID_PASSWORD     UserErrorReason = 6
	UserErrorReason_PASSWORD_TOO_WEAK    UserErrorReason = 7
	UserErrorReason_INVALID_EMAIL_FORMAT UserErrorReason = 8
	UserErrorReason_USERNAME_TOO_SHORT   UserErrorReason = 9
	UserErrorReason_USERNAME_TOO_LONG    UserErrorReason = 10
	UserErrorReason_PERMISSION_DENIED    UserErrorReason = 11
)

// Enum value maps for UserErrorReason.
var (
	UserErrorReason_name = map[int32]string{
		0:  "USER_UNSPECIFIED",
		1:  "USER_NOT_FOUND",
		2:  "USER_ALREADY_EXISTS",
		3:  "EMAIL_ALREADY_EXISTS",
		4:  "INVALID_CREDENTIALS",
		5:  "USER_INACTIVE",
		6:  "INVALID_PASSWORD",
		7:  "PASSWORD_TOO_WEAK",
		8:  "INVALID_EMAIL_FORMAT",
		9:  "USERNAME_TOO_SHORT",
		10: "USERNAME_TOO_LONG",
		11: "PERMISSION_DENIED",
	}
	UserErrorReason_value = map[string]int32{
		"USER_UNSPECIFIED":     0,
		"USER_NOT_FOUND":       1,
		"USER_ALREADY_EXISTS":  2,
		"EMAIL_ALREADY_EXISTS": 3,
		"INVALID_CREDENTIALS":  4,
		"USER_INACTIVE":        5,
		"INVALID_PASSWORD":     6,
		"PASSWORD_TOO_WEAK":    7,
		"INVALID_EMAIL_FORMAT": 8,
		"USERNAME_TOO_SHORT":   9,
		"USERNAME_TOO_LONG":    10,
		"PERMISSION_DENIED":    11,
	}
)

func (x UserErrorReason) Enum() *UserErrorReason {
	p := new(UserErrorReason)
	*p = x
	return p
}

func (x UserErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_errors_v1_errors_proto_enumTypes[0].Descriptor()
}

func (UserErrorReason) Type() protoreflect.EnumType {
	return &file_api_errors_v1_errors_proto_enumTypes[0]
}

func (x UserErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserErrorReason.Descriptor instead.
func (UserErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_errors_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_api_errors_v1_errors_proto protoreflect.FileDescriptor

const file_api_errors_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/errors/v1/errors.proto\x12\rapi.errors.v1\x1a\x13errors/errors.proto*\xe9\x02\n" +
	"\x0fUserErrorReason\x12\x14\n" +
	"\x10USER_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\x01\x1a\x04\xa8E\x94\x03\x12\x1d\n" +
	"\x13USER_ALREADY_EXISTS\x10\x02\x1a\x04\xa8E\x99\x03\x12\x1e\n" +
	"\x14EMAIL_ALREADY_EXISTS\x10\x03\x1a\x04\xa8E\x99\x03\x12\x1d\n" +
	"\x13INVALID_CREDENTIALS\x10\x04\x1a\x04\xa8E\x91\x03\x12\x17\n" +
	"\rUSER_INACTIVE\x10\x05\x1a\x04\xa8E\x93\x03\x12\x1a\n" +
	"\x10INVALID_PASSWORD\x10\x06\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11PASSWORD_TOO_WEAK\x10\a\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x14INVALID_EMAIL_FORMAT\x10\b\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12USERNAME_TOO_SHORT\x10\t\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11USERNAME_TOO_LONG\x10\n" +
	"\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11PERMISSION_DENIED\x10\v\x1a\x04\xa8E\x93\x03B5Z3github.com/Sakuya1998/domain-admin/api/errors/v1;v1b\x06proto3"

var (
	file_api_errors_v1_errors_proto_rawDescOnce sync.Once
	file_api_errors_v1_errors_proto_rawDescData []byte
)

func file_api_errors_v1_errors_proto_rawDescGZIP() []byte {
	file_api_errors_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_errors_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_errors_v1_errors_proto_rawDesc), len(file_api_errors_v1_errors_proto_rawDesc)))
	})
	return file_api_errors_v1_errors_proto_rawDescData
}

var file_api_errors_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_errors_v1_errors_proto_goTypes = []any{
	(UserErrorReason)(0), // 0: api.errors.v1.UserErrorReason
}
var file_api_errors_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_errors_v1_errors_proto_init() }
func file_api_errors_v1_errors_proto_init() {
	if File_api_errors_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_errors_v1_errors_proto_rawDesc), len(file_api_errors_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errors_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_errors_v1_errors_proto_depIdxs,
		EnumInfos:         file_api_errors_v1_errors_proto_enumTypes,
	}.Build()
	File_api_errors_v1_errors_proto = out.File
	file_api_errors_v1_errors_proto_goTypes = nil
	file_api_errors_v1_errors_proto_depIdxs = nil
}
