// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/user/v1/user.proto

package v1

import (
	v1 "github.com/Sakuya1998/domain-admin/api/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // 邮箱
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          v1.UserRole            `protobuf:"varint,6,opt,name=role,proto3,enum=api.common.v1.UserRole" json:"role,omitempty"`
	Status        v1.Status              `protobuf:"varint,7,opt,name=status,proto3,enum=api.common.v1.Status" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLoginAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetRole() v1.UserRole {
	if x != nil {
		return x.Role
	}
	return v1.UserRole(0)
}

func (x *UserInfo) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserInfo) GetLastLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginAt
	}
	return nil
}

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 注册响应
type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.Reply              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReply) GetBase() *v1.Reply {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterReply) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// 登录请求
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Account:
	//
	//	*LoginRequest_Username
	//	*LoginRequest_Email
	Account       isLoginRequest_Account `protobuf_oneof:"account"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetAccount() isLoginRequest_Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Account.(*LoginRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Account.(*LoginRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type isLoginRequest_Account interface {
	isLoginRequest_Account()
}

type LoginRequest_Username struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*LoginRequest_Username) isLoginRequest_Account() {}

func (*LoginRequest_Email) isLoginRequest_Account() {}

// 登录响应
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.Reply              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReply) GetBase() *v1.Reply {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// 登出请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 登出响应
type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.Reply              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutReply) GetBase() *v1.Reply {
	if x != nil {
		return x.Base
	}
	return nil
}

// 更新用户信息请求
type UpdateUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserInfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserInfoRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 更新用户密码请求
type UpdateUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordRequest) Reset() {
	*x = UpdateUserPasswordRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordRequest) ProtoMessage() {}

func (x *UpdateUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserPasswordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdateUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// 更新用户状态请求
type UpdateUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        v1.Status              `protobuf:"varint,2,opt,name=status,proto3,enum=api.common.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusRequest) Reset() {
	*x = UpdateUserStatusRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusRequest) ProtoMessage() {}

func (x *UpdateUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserStatusRequest) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

// 获取用户列表请求
type GetUserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Role          v1.UserRole            `protobuf:"varint,3,opt,name=role,proto3,enum=api.common.v1.UserRole" json:"role,omitempty"`
	Status        v1.Status              `protobuf:"varint,4,opt,name=status,proto3,enum=api.common.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListRequest) Reset() {
	*x = GetUserListRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListRequest) ProtoMessage() {}

func (x *GetUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListRequest.ProtoReflect.Descriptor instead.
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserListRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetUserListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetUserListRequest) GetRole() v1.UserRole {
	if x != nil {
		return x.Role
	}
	return v1.UserRole(0)
}

func (x *GetUserListRequest) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

// 获取用户列表响应
type GetUserListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.Reply              `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Page          *v1.PageReply          `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Users         []*UserInfo            `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListReply) Reset() {
	*x = GetUserListReply{}
	mi := &file_api_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListReply) ProtoMessage() {}

func (x *GetUserListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListReply.ProtoReflect.Descriptor instead.
func (*GetUserListReply) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserListReply) GetBase() *v1.Reply {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetUserListReply) GetPage() *v1.PageReply {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetUserListReply) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

// 添加用户请求
type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          v1.UserRole            `protobuf:"varint,5,opt,name=role,proto3,enum=api.common.v1.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *AddUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddUserRequest) GetRole() v1.UserRole {
	if x != nil {
		return x.Role
	}
	return v1.UserRole(0)
}

// 重置用户密码请求
type ResetUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUserPasswordRequest) Reset() {
	*x = ResetUserPasswordRequest{}
	mi := &file_api_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUserPasswordRequest) ProtoMessage() {}

func (x *ResetUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *ResetUserPasswordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResetUserPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

var File_api_user_v1_user_proto protoreflect.FileDescriptor

const file_api_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x16api/user/v1/user.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aapi/common/v1/common.proto\x1a\x17validate/validate.proto\"\xc6\x03\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x126\n" +
	"\busername\x18\x02 \x01(\tB\x1a\xfaB\x17r\x15\x10\x03\x18\x142\x0f^[a-zA-Z0-9_]+$R\busername\x12\x1d\n" +
	"\x05email\x18\x03 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12)\n" +
	"\x05phone\x18\x04 \x01(\tB\x13\xfaB\x10r\x0e2\f^1[0-9]{10}$R\x05phone\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12+\n" +
	"\x04role\x18\x06 \x01(\x0e2\x17.api.common.v1.UserRoleR\x04role\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.api.common.v1.StatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rlast_login_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vlastLoginAt\"\xce\x01\n" +
	"\x0fRegisterRequest\x126\n" +
	"\busername\x18\x01 \x01(\tB\x1a\xfaB\x17r\x15\x10\x03\x18\x142\x0f^[a-zA-Z0-9_]+$R\busername\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12)\n" +
	"\x05phone\x18\x03 \x01(\tB\x13\xfaB\x10r\x0e2\f^1[0-9]{10}$R\x05phone\x129\n" +
	"\bpassword\x18\x04 \x01(\tB\x1d\xfaB\x1ar\x18\x10\b\x18\x142\x12^[A-Za-z\\d]{8,20}$R\bpassword\"\x83\x01\n" +
	"\rRegisterReply\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.api.common.v1.ReplyR\x04base\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x122\n" +
	"\tuser_info\x18\x03 \x01(\v2\x15.api.user.v1.UserInfoR\buserInfo\"\x88\x01\n" +
	"\fLoginRequest\x12'\n" +
	"\busername\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18\x14H\x00R\busername\x12\x1f\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01H\x00R\x05email\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpasswordB\t\n" +
	"\aaccount\"\x80\x01\n" +
	"\n" +
	"LoginReply\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.api.common.v1.ReplyR\x04base\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x122\n" +
	"\tuser_info\x18\x03 \x01(\v2\x15.api.user.v1.UserInfoR\buserInfo\"%\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"7\n" +
	"\vLogoutReply\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.api.common.v1.ReplyR\x04base\"\x99\x01\n" +
	"\x15UpdateUserInfoRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\x05email\x18\x03 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"\x8c\x01\n" +
	"\x19UpdateUserPasswordRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12*\n" +
	"\fold_password\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\voldPassword\x12*\n" +
	"\fnew_password\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\vnewPassword\"a\n" +
	"\x17UpdateUserStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.api.common.v1.StatusR\x06status\"\xba\x01\n" +
	"\x12GetUserListRequest\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12+\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.api.common.v1.UserRoleR\x04role\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.api.common.v1.StatusR\x06status\"\x97\x01\n" +
	"\x10GetUserListReply\x12(\n" +
	"\x04base\x18\x01 \x01(\v2\x14.api.common.v1.ReplyR\x04base\x12,\n" +
	"\x04page\x18\x02 \x01(\v2\x18.api.common.v1.PageReplyR\x04page\x12+\n" +
	"\x05users\x18\x03 \x03(\v2\x15.api.user.v1.UserInfoR\x05users\"\xbc\x01\n" +
	"\x0eAddUserRequest\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\busername\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12+\n" +
	"\x04role\x18\x05 \x01(\x0e2\x17.api.common.v1.UserRoleR\x04role\"_\n" +
	"\x18ResetUserPasswordRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12*\n" +
	"\fnew_password\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\vnewPassword2\x95\t\n" +
	"\x04User\x12g\n" +
	"\bRegister\x12\x1c.api.user.v1.RegisterRequest\x1a\x1a.api.user.v1.RegisterReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/users/register\x12[\n" +
	"\x05Login\x12\x19.api.user.v1.LoginRequest\x1a\x17.api.user.v1.LoginReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/users/login\x12_\n" +
	"\x06Logout\x12\x1a.api.user.v1.LogoutRequest\x1a\x18.api.user.v1.LogoutReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/users/logout\x12Z\n" +
	"\vGetUserInfo\x12\x18.api.common.v1.IDRequest\x1a\x15.api.user.v1.UserInfo\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12j\n" +
	"\x0eUpdateUserInfo\x12\".api.user.v1.UpdateUserInfoRequest\x1a\x15.api.user.v1.UserInfo\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/users/{id}\x12\x7f\n" +
	"\x12UpdateUserPassword\x12&.api.user.v1.UpdateUserPasswordRequest\x1a\x19.api.common.v1.EmptyReply\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/api/v1/users/{id}/password\x12y\n" +
	"\x10UpdateUserStatus\x12$.api.user.v1.UpdateUserStatusRequest\x1a\x19.api.common.v1.EmptyReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/v1/users/{id}/status\x12d\n" +
	"\vGetUserList\x12\x1f.api.user.v1.GetUserListRequest\x1a\x1d.api.user.v1.GetUserListReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/users\x12W\n" +
	"\aAddUser\x12\x1b.api.user.v1.AddUserRequest\x1a\x15.api.user.v1.UserInfo\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12]\n" +
	"\n" +
	"DeleteUser\x12\x18.api.common.v1.IDRequest\x1a\x19.api.common.v1.EmptyReply\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/users/{id}\x12\x83\x01\n" +
	"\x11ResetUserPassword\x12%.api.user.v1.ResetUserPasswordRequest\x1a\x19.api.common.v1.EmptyReply\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/v1/users/{id}/reset-passwordBB\n" +
	"\vapi.user.v1P\x01Z1github.com/Sakuya1998/domain-admin/api/user/v1;v1b\x06proto3"

var (
	file_api_user_v1_user_proto_rawDescOnce sync.Once
	file_api_user_v1_user_proto_rawDescData []byte
)

func file_api_user_v1_user_proto_rawDescGZIP() []byte {
	file_api_user_v1_user_proto_rawDescOnce.Do(func() {
		file_api_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)))
	})
	return file_api_user_v1_user_proto_rawDescData
}

var file_api_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_user_v1_user_proto_goTypes = []any{
	(*UserInfo)(nil),                  // 0: api.user.v1.UserInfo
	(*RegisterRequest)(nil),           // 1: api.user.v1.RegisterRequest
	(*RegisterReply)(nil),             // 2: api.user.v1.RegisterReply
	(*LoginRequest)(nil),              // 3: api.user.v1.LoginRequest
	(*LoginReply)(nil),                // 4: api.user.v1.LoginReply
	(*LogoutRequest)(nil),             // 5: api.user.v1.LogoutRequest
	(*LogoutReply)(nil),               // 6: api.user.v1.LogoutReply
	(*UpdateUserInfoRequest)(nil),     // 7: api.user.v1.UpdateUserInfoRequest
	(*UpdateUserPasswordRequest)(nil), // 8: api.user.v1.UpdateUserPasswordRequest
	(*UpdateUserStatusRequest)(nil),   // 9: api.user.v1.UpdateUserStatusRequest
	(*GetUserListRequest)(nil),        // 10: api.user.v1.GetUserListRequest
	(*GetUserListReply)(nil),          // 11: api.user.v1.GetUserListReply
	(*AddUserRequest)(nil),            // 12: api.user.v1.AddUserRequest
	(*ResetUserPasswordRequest)(nil),  // 13: api.user.v1.ResetUserPasswordRequest
	(v1.UserRole)(0),                  // 14: api.common.v1.UserRole
	(v1.Status)(0),                    // 15: api.common.v1.Status
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
	(*v1.Reply)(nil),                  // 17: api.common.v1.Reply
	(*v1.PageRequest)(nil),            // 18: api.common.v1.PageRequest
	(*v1.PageReply)(nil),              // 19: api.common.v1.PageReply
	(*v1.IDRequest)(nil),              // 20: api.common.v1.IDRequest
	(*v1.EmptyReply)(nil),             // 21: api.common.v1.EmptyReply
}
var file_api_user_v1_user_proto_depIdxs = []int32{
	14, // 0: api.user.v1.UserInfo.role:type_name -> api.common.v1.UserRole
	15, // 1: api.user.v1.UserInfo.status:type_name -> api.common.v1.Status
	16, // 2: api.user.v1.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: api.user.v1.UserInfo.updated_at:type_name -> google.protobuf.Timestamp
	16, // 4: api.user.v1.UserInfo.last_login_at:type_name -> google.protobuf.Timestamp
	17, // 5: api.user.v1.RegisterReply.base:type_name -> api.common.v1.Reply
	0,  // 6: api.user.v1.RegisterReply.user_info:type_name -> api.user.v1.UserInfo
	17, // 7: api.user.v1.LoginReply.base:type_name -> api.common.v1.Reply
	0,  // 8: api.user.v1.LoginReply.user_info:type_name -> api.user.v1.UserInfo
	17, // 9: api.user.v1.LogoutReply.base:type_name -> api.common.v1.Reply
	15, // 10: api.user.v1.UpdateUserStatusRequest.status:type_name -> api.common.v1.Status
	18, // 11: api.user.v1.GetUserListRequest.page:type_name -> api.common.v1.PageRequest
	14, // 12: api.user.v1.GetUserListRequest.role:type_name -> api.common.v1.UserRole
	15, // 13: api.user.v1.GetUserListRequest.status:type_name -> api.common.v1.Status
	17, // 14: api.user.v1.GetUserListReply.base:type_name -> api.common.v1.Reply
	19, // 15: api.user.v1.GetUserListReply.page:type_name -> api.common.v1.PageReply
	0,  // 16: api.user.v1.GetUserListReply.users:type_name -> api.user.v1.UserInfo
	14, // 17: api.user.v1.AddUserRequest.role:type_name -> api.common.v1.UserRole
	1,  // 18: api.user.v1.User.Register:input_type -> api.user.v1.RegisterRequest
	3,  // 19: api.user.v1.User.Login:input_type -> api.user.v1.LoginRequest
	5,  // 20: api.user.v1.User.Logout:input_type -> api.user.v1.LogoutRequest
	20, // 21: api.user.v1.User.GetUserInfo:input_type -> api.common.v1.IDRequest
	7,  // 22: api.user.v1.User.UpdateUserInfo:input_type -> api.user.v1.UpdateUserInfoRequest
	8,  // 23: api.user.v1.User.UpdateUserPassword:input_type -> api.user.v1.UpdateUserPasswordRequest
	9,  // 24: api.user.v1.User.UpdateUserStatus:input_type -> api.user.v1.UpdateUserStatusRequest
	10, // 25: api.user.v1.User.GetUserList:input_type -> api.user.v1.GetUserListRequest
	12, // 26: api.user.v1.User.AddUser:input_type -> api.user.v1.AddUserRequest
	20, // 27: api.user.v1.User.DeleteUser:input_type -> api.common.v1.IDRequest
	13, // 28: api.user.v1.User.ResetUserPassword:input_type -> api.user.v1.ResetUserPasswordRequest
	2,  // 29: api.user.v1.User.Register:output_type -> api.user.v1.RegisterReply
	4,  // 30: api.user.v1.User.Login:output_type -> api.user.v1.LoginReply
	6,  // 31: api.user.v1.User.Logout:output_type -> api.user.v1.LogoutReply
	0,  // 32: api.user.v1.User.GetUserInfo:output_type -> api.user.v1.UserInfo
	0,  // 33: api.user.v1.User.UpdateUserInfo:output_type -> api.user.v1.UserInfo
	21, // 34: api.user.v1.User.UpdateUserPassword:output_type -> api.common.v1.EmptyReply
	21, // 35: api.user.v1.User.UpdateUserStatus:output_type -> api.common.v1.EmptyReply
	11, // 36: api.user.v1.User.GetUserList:output_type -> api.user.v1.GetUserListReply
	0,  // 37: api.user.v1.User.AddUser:output_type -> api.user.v1.UserInfo
	21, // 38: api.user.v1.User.DeleteUser:output_type -> api.common.v1.EmptyReply
	21, // 39: api.user.v1.User.ResetUserPassword:output_type -> api.common.v1.EmptyReply
	29, // [29:40] is the sub-list for method output_type
	18, // [18:29] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_user_v1_user_proto_init() }
func file_api_user_v1_user_proto_init() {
	if File_api_user_v1_user_proto != nil {
		return
	}
	file_api_user_v1_user_proto_msgTypes[3].OneofWrappers = []any{
		(*LoginRequest_Username)(nil),
		(*LoginRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_user_proto_rawDesc), len(file_api_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_user_proto_goTypes,
		DependencyIndexes: file_api_user_v1_user_proto_depIdxs,
		MessageInfos:      file_api_user_v1_user_proto_msgTypes,
	}.Build()
	File_api_user_v1_user_proto = out.File
	file_api_user_v1_user_proto_goTypes = nil
	file_api_user_v1_user_proto_depIdxs = nil
}
