server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: domain_admin:domain_admin@tcp(izayoisakuya.top:3307)/domain_admin?parseTime=True&loc=Local
  redis:
    addr: izayoisakuya.top:6379
    password: redis_PZBCDE
    read_timeout: 0.2s
    write_timeout: 0.2s
