server:
  port: 8000
  host: 0.0.0.0
  timeout: 1s

database:
  driver: mysql
  host: izayoisakuya.top
  port: 3307
  user: domain_admin
  password: domain_admin
  db: domain_admin
  prefix: domain_
  singular: true
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 10
  log_level: info
  
redis:
  addr: izayoisakuya.top:6379
  password: redis_PZBCDE
  db: 0
  read_timeout: 0.2s
  write_timeout: 0.2s

log:
  level: info
  format: json
  output: both
  file_path: logs/app.log
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
  development: false

jwt:
  secret: domain_admin
  expiration: 24h

cloudprovider:
  - type: alibaba
    access_key:
    access_secret:

  - type: tencent
    access_key:
    access_secret:

  - type: cloudflare
    access_key:
    access_secret:

otel:
  endpoint: 0.0.0.0:4318
  service_name: domain-admin
  service_version: v1.0.0
  service_instance_id: domain-admin-1




