// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/common/v1/common.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状态枚举
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
	Status_STATUS_ARCHIVED    Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_ARCHIVED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
		"STATUS_ARCHIVED":    3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// 操作类型枚举
type OperationType int32

const (
	OperationType_OPERATION_TYPE_UNSPECIFIED  OperationType = 0
	OperationType_OPERATION_TYPE_CREATE       OperationType = 1
	OperationType_OPERATION_TYPE_UPDATE       OperationType = 2
	OperationType_OPERATION_TYPE_DELETE       OperationType = 3
	OperationType_OPERATION_TYPE_BATCH_DELETE OperationType = 4
	OperationType_OPERATION_TYPE_EXPORT       OperationType = 5
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_CREATE",
		2: "OPERATION_TYPE_UPDATE",
		3: "OPERATION_TYPE_DELETE",
		4: "OPERATION_TYPE_BATCH_DELETE",
		5: "OPERATION_TYPE_EXPORT",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED":  0,
		"OPERATION_TYPE_CREATE":       1,
		"OPERATION_TYPE_UPDATE":       2,
		"OPERATION_TYPE_DELETE":       3,
		"OPERATION_TYPE_BATCH_DELETE": 4,
		"OPERATION_TYPE_EXPORT":       5,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{1}
}

// 用户角色枚举
type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_ADMIN       UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_ADMIN":       2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[2].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[2]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{2}
}

// SSL类型枚举
type SSLType int32

const (
	SSLType_SSL_TYPE_UNSPECIFIED SSLType = 0
	SSLType_SSL_TYPE_TLS         SSLType = 1
	SSLType_SSL_TYPE_STARTTLS    SSLType = 2
)

// Enum value maps for SSLType.
var (
	SSLType_name = map[int32]string{
		0: "SSL_TYPE_UNSPECIFIED",
		1: "SSL_TYPE_TLS",
		2: "SSL_TYPE_STARTTLS",
	}
	SSLType_value = map[string]int32{
		"SSL_TYPE_UNSPECIFIED": 0,
		"SSL_TYPE_TLS":         1,
		"SSL_TYPE_STARTTLS":    2,
	}
)

func (x SSLType) Enum() *SSLType {
	p := new(SSLType)
	*p = x
	return p
}

func (x SSLType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSLType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[3].Descriptor()
}

func (SSLType) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[3]
}

func (x SSLType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SSLType.Descriptor instead.
func (SSLType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{3}
}

// 通知类型枚举
type NotifyType int32

const (
	NotifyType_NOTIFY_TYPE_UNSPECIFIED NotifyType = 0
	NotifyType_NOTIFY_TYPE_EMAIL       NotifyType = 1
	NotifyType_NOTIFY_TYPE_WEBHOOK     NotifyType = 2
	NotifyType_NOTIFY_TYPE_WECHAT_WORK NotifyType = 3
	NotifyType_NOTIFY_TYPE_DINGTALK    NotifyType = 4
	NotifyType_NOTIFY_TYPE_FEISHU      NotifyType = 5
	NotifyType_NOTIFY_TYPE_TELEGRAM    NotifyType = 6
)

// Enum value maps for NotifyType.
var (
	NotifyType_name = map[int32]string{
		0: "NOTIFY_TYPE_UNSPECIFIED",
		1: "NOTIFY_TYPE_EMAIL",
		2: "NOTIFY_TYPE_WEBHOOK",
		3: "NOTIFY_TYPE_WECHAT_WORK",
		4: "NOTIFY_TYPE_DINGTALK",
		5: "NOTIFY_TYPE_FEISHU",
		6: "NOTIFY_TYPE_TELEGRAM",
	}
	NotifyType_value = map[string]int32{
		"NOTIFY_TYPE_UNSPECIFIED": 0,
		"NOTIFY_TYPE_EMAIL":       1,
		"NOTIFY_TYPE_WEBHOOK":     2,
		"NOTIFY_TYPE_WECHAT_WORK": 3,
		"NOTIFY_TYPE_DINGTALK":    4,
		"NOTIFY_TYPE_FEISHU":      5,
		"NOTIFY_TYPE_TELEGRAM":    6,
	}
)

func (x NotifyType) Enum() *NotifyType {
	p := new(NotifyType)
	*p = x
	return p
}

func (x NotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[4].Descriptor()
}

func (NotifyType) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[4]
}

func (x NotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyType.Descriptor instead.
func (NotifyType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{4}
}

// 事件类型枚举
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED     EventType = 0
	EventType_EVENT_TYPE_SSL_CERT_EXPIRE EventType = 1
	EventType_EVENT_TYPE_DOMAIN_EXPIRE   EventType = 2
	EventType_EVENT_TYPE_MONITOR_DOWN    EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_SSL_CERT_EXPIRE",
		2: "EVENT_TYPE_DOMAIN_EXPIRE",
		3: "EVENT_TYPE_MONITOR_DOWN",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_SSL_CERT_EXPIRE": 1,
		"EVENT_TYPE_DOMAIN_EXPIRE":   2,
		"EVENT_TYPE_MONITOR_DOWN":    3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[5].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[5]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{5}
}

// 监控状态枚举
type MonitorStatus int32

const (
	MonitorStatus_MONITOR_STATUS_UNSPECIFIED MonitorStatus = 0
	MonitorStatus_MONITOR_STATUS_UP          MonitorStatus = 1
	MonitorStatus_MONITOR_STATUS_DOWN        MonitorStatus = 2
	MonitorStatus_MONITOR_STATUS_UNKNOWN     MonitorStatus = 3
)

// Enum value maps for MonitorStatus.
var (
	MonitorStatus_name = map[int32]string{
		0: "MONITOR_STATUS_UNSPECIFIED",
		1: "MONITOR_STATUS_UP",
		2: "MONITOR_STATUS_DOWN",
		3: "MONITOR_STATUS_UNKNOWN",
	}
	MonitorStatus_value = map[string]int32{
		"MONITOR_STATUS_UNSPECIFIED": 0,
		"MONITOR_STATUS_UP":          1,
		"MONITOR_STATUS_DOWN":        2,
		"MONITOR_STATUS_UNKNOWN":     3,
	}
)

func (x MonitorStatus) Enum() *MonitorStatus {
	p := new(MonitorStatus)
	*p = x
	return p
}

func (x MonitorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonitorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_v1_common_proto_enumTypes[6].Descriptor()
}

func (MonitorStatus) Type() protoreflect.EnumType {
	return &file_api_common_v1_common_proto_enumTypes[6]
}

func (x MonitorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonitorStatus.Descriptor instead.
func (MonitorStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{6}
}

// 响应
type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                                                  // 状态码(数字)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                                             // 响应消息(文字描述)
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // 时间戳
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                                              // 追踪ID(用于分布式链路追踪)
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                        // 请求ID(用于请求追踪)
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据(自定义字段)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Reply) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Reply) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Reply) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Reply) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 分页请求参数 (适用于列表查询)
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`     // 通用搜索词
	Filters       []string               `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty"` // 过滤条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_api_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PageRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *PageRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PageRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// 分页响应结构
type PageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"` // 更明确的字段名
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`             // 替代page_size
	TotalItems    int64                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`    // 替代total
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	HasNext       bool                   `protobuf:"varint,5,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"` // 新增辅助字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageReply) Reset() {
	*x = PageReply{}
	mi := &file_api_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageReply) ProtoMessage() {}

func (x *PageReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageReply.ProtoReflect.Descriptor instead.
func (*PageReply) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PageReply) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PageReply) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *PageReply) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PageReply) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PageReply) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

// ID请求
type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_api_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *IDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// IDs请求
type IDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDsRequest) Reset() {
	*x = IDsRequest{}
	mi := &file_api_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsRequest) ProtoMessage() {}

func (x *IDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsRequest.ProtoReflect.Descriptor instead.
func (*IDsRequest) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *IDsRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// 空响应
type EmptyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyReply) Reset() {
	*x = EmptyReply{}
	mi := &file_api_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReply) ProtoMessage() {}

func (x *EmptyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReply.ProtoReflect.Descriptor instead.
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return file_api_common_v1_common_proto_rawDescGZIP(), []int{5}
}

var File_api_common_v1_common_proto protoreflect.FileDescriptor

const file_api_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/common/v1/common.proto\x12\rapi.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xa6\x02\n" +
	"\x05Reply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12>\n" +
	"\bmetadata\x18\x06 \x03(\v2\".api.common.v1.Reply.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x01\n" +
	"\vPageRequest\x12\x1e\n" +
	"\x04page\x18\x01 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90N(\x01R\x04page\x12'\n" +
	"\tpage_size\x18\x02 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\xc8\x01(\x01R\bpageSize\x12 \n" +
	"\asort_by\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x18@R\x06sortBy\x12<\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tB\x1d\xfaB\x1ar\x18R\x00R\x03ascR\x04descR\x03ASCR\x04DESCR\tsortOrder\x12\x1e\n" +
	"\x05query\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x18\x80\x01R\x05query\x12\x18\n" +
	"\afilters\x18\x06 \x03(\tR\afilters\"\xa6\x01\n" +
	"\tPageReply\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x03R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12\x19\n" +
	"\bhas_next\x18\x05 \x01(\bR\ahasNext\"$\n" +
	"\tIDRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"(\n" +
	"\n" +
	"IDsRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x03B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\f\n" +
	"\n" +
	"EmptyReply*]\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x13\n" +
	"\x0fSTATUS_ARCHIVED\x10\x03*\xbc\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_TYPE_CREATE\x10\x01\x12\x19\n" +
	"\x15OPERATION_TYPE_UPDATE\x10\x02\x12\x19\n" +
	"\x15OPERATION_TYPE_DELETE\x10\x03\x12\x1f\n" +
	"\x1bOPERATION_TYPE_BATCH_DELETE\x10\x04\x12\x19\n" +
	"\x15OPERATION_TYPE_EXPORT\x10\x05*N\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02*L\n" +
	"\aSSLType\x12\x18\n" +
	"\x14SSL_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSSL_TYPE_TLS\x10\x01\x12\x15\n" +
	"\x11SSL_TYPE_STARTTLS\x10\x02*\xc2\x01\n" +
	"\n" +
	"NotifyType\x12\x1b\n" +
	"\x17NOTIFY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NOTIFY_TYPE_EMAIL\x10\x01\x12\x17\n" +
	"\x13NOTIFY_TYPE_WEBHOOK\x10\x02\x12\x1b\n" +
	"\x17NOTIFY_TYPE_WECHAT_WORK\x10\x03\x12\x18\n" +
	"\x14NOTIFY_TYPE_DINGTALK\x10\x04\x12\x16\n" +
	"\x12NOTIFY_TYPE_FEISHU\x10\x05\x12\x18\n" +
	"\x14NOTIFY_TYPE_TELEGRAM\x10\x06*\x82\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEVENT_TYPE_SSL_CERT_EXPIRE\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_DOMAIN_EXPIRE\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_MONITOR_DOWN\x10\x03*{\n" +
	"\rMonitorStatus\x12\x1e\n" +
	"\x1aMONITOR_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MONITOR_STATUS_UP\x10\x01\x12\x17\n" +
	"\x13MONITOR_STATUS_DOWN\x10\x02\x12\x1a\n" +
	"\x16MONITOR_STATUS_UNKNOWN\x10\x03BF\n" +
	"\rapi.common.v1P\x01Z3github.com/Sakuya1998/domain-admin/api/common/v1;v1b\x06proto3"

var (
	file_api_common_v1_common_proto_rawDescOnce sync.Once
	file_api_common_v1_common_proto_rawDescData []byte
)

func file_api_common_v1_common_proto_rawDescGZIP() []byte {
	file_api_common_v1_common_proto_rawDescOnce.Do(func() {
		file_api_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)))
	})
	return file_api_common_v1_common_proto_rawDescData
}

var file_api_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_api_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_common_v1_common_proto_goTypes = []any{
	(Status)(0),                   // 0: api.common.v1.Status
	(OperationType)(0),            // 1: api.common.v1.OperationType
	(UserRole)(0),                 // 2: api.common.v1.UserRole
	(SSLType)(0),                  // 3: api.common.v1.SSLType
	(NotifyType)(0),               // 4: api.common.v1.NotifyType
	(EventType)(0),                // 5: api.common.v1.EventType
	(MonitorStatus)(0),            // 6: api.common.v1.MonitorStatus
	(*Reply)(nil),                 // 7: api.common.v1.Reply
	(*PageRequest)(nil),           // 8: api.common.v1.PageRequest
	(*PageReply)(nil),             // 9: api.common.v1.PageReply
	(*IDRequest)(nil),             // 10: api.common.v1.IDRequest
	(*IDsRequest)(nil),            // 11: api.common.v1.IDsRequest
	(*EmptyReply)(nil),            // 12: api.common.v1.EmptyReply
	nil,                           // 13: api.common.v1.Reply.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_api_common_v1_common_proto_depIdxs = []int32{
	14, // 0: api.common.v1.Reply.timestamp:type_name -> google.protobuf.Timestamp
	13, // 1: api.common.v1.Reply.metadata:type_name -> api.common.v1.Reply.MetadataEntry
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_common_v1_common_proto_init() }
func file_api_common_v1_common_proto_init() {
	if File_api_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_v1_common_proto_rawDesc), len(file_api_common_v1_common_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_v1_common_proto_goTypes,
		DependencyIndexes: file_api_common_v1_common_proto_depIdxs,
		EnumInfos:         file_api_common_v1_common_proto_enumTypes,
		MessageInfos:      file_api_common_v1_common_proto_msgTypes,
	}.Build()
	File_api_common_v1_common_proto = out.File
	file_api_common_v1_common_proto_goTypes = nil
	file_api_common_v1_common_proto_depIdxs = nil
}
